const Database = require('better-sqlite3');
const db = new Database('./server/db/torneos.db', {readonly:true});
console.log('=== USERS ===');
console.log(JSON.stringify(db.prepare('SELECT id, nickname, email, country, continent FROM users').all(), null, 2));
console.log('=== TOURNAMENTS ===');
console.log(JSON.stringify(db.prepare('SELECT id, name, status, bracket_size, elimination_type, game_type, creator_id, is_public FROM tournaments').all(), null, 2));
console.log('=== PARTICIPANTS ===');
console.log(JSON.stringify(db.prepare('SELECT id, tournament_id, user_id, name FROM participants').all(), null, 2));
console.log('=== MATCHES ===');
console.log(JSON.stringify(db.prepare('SELECT id, tournament_id, match_order, round, bracket_type, status, player1_id, player2_id, winner_id FROM matches').all(), null, 2));
db.close();
